# This is a basic workflow to help you get started with Actions

name: Python Calculator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m pytest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1

#      - name: Run pytest
#        uses: pavelzw/pytest-action@v1
#        with:
#          verbose: true
#          emoji: true
#          job-summary: true
#          custom-arguments: '-q'
